const STATUS_CODE = {
  SERVER_ERROR_CODE: 500,
  BAD_REQUEST_CODE: 400,
  NOT_FOUND_CODE: 404,
  UNAUTHORIZED_CODE: 401,
  CONFLICT_CODE: 409,
  FORBIDDEN_CODE: 403,
};

module.exports = {
  STATUS_CODE,
};